# Generated by Django 4.2 on 2023-04-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='qr_code',
            field=models.CharField(max_length=60),
        ),
    ]
